gpu-functions-mojo/.gitignore, gpu-functions-mojo/README.md, gpu-functions-mojo/grayscale.mojo, gpu-functions-mojo/mandelbrot.mojo, gpu-functions-mojo/metadata.yaml, gpu-functions-mojo/naive_matrix_multiplication.mojo, gpu-functions-mojo/pyproject.toml, gpu-functions-mojo/vector_addition.mojo
Adds a recipe that encapsulates the very basic GPU programming model in MAX and Mojo of defining functions in Mojo and dispatching them on the GPU directly with the MAX Driver API. This is a programming model very familiar to CUDA developers, and can be an initial entry point for those mapping how to program in MAX to how they would have approached a problem in CUDA.
Examples are sourced from https://github.com/modular/max/tree/main/examples/gpu_functions
=> Add recipe: GPU functions in Mojo

custom-ops-introduction/.gitignore, custom-ops-introduction/README.md, custom-ops-introduction/add_one.py, custom-ops-introduction/mandelbrot.py, custom-ops-introduction/metadata.yaml, custom-ops-introduction/operations/__init__.mojo, custom-ops-introduction/operations/add_one.mojo, custom-ops-introduction/operations/mandelbrot.mojo, custom-ops-introduction/operations/vector_addition.mojo, custom-ops-introduction/pyproject.toml, custom-ops-introduction/vector_addition.py
Adds the first of a series of three planned recipes on custom operations (an introduction, optimizing matrix multiplications, and advanced AI operations: top-K sampling and FlashAttention 2).
The examples here are drawn from [the public MAX custom operation examples](https://github.com/modular/max/tree/main/examples/custom_ops) with some cleanups that will be brought back to those original examples.
=> Add recipe: an introduction to custom ops

custom-ops-ai-applications/.gitignore, custom-ops-ai-applications/README.md, custom-ops-ai-applications/benchmarks.mojo, custom-ops-ai-applications/fused_attention.py, custom-ops-ai-applications/metadata.yaml, custom-ops-ai-applications/operations/__init__.mojo, custom-ops-ai-applications/operations/fused_attention.mojo, custom-ops-ai-applications/operations/top_k.mojo, custom-ops-ai-applications/pyproject.toml, custom-ops-ai-applications/top_k.py
Adds a recipe for the more advanced custom ops examples: top-K token sampling and a fused attention layer.
Marking this as a draft for now, because significant additions need to be made to the README to fill in relevant information about the two operations and what people should learn as they examine the code. The rest of the scaffolding is there, as well as all example code and what's needed to run them.
=> Add recipe: custom ops with applications in AI models

custom-ops-ai-applications/benchmarks.mojo, custom-ops-ai-applications/operations/fused_attention.mojo, custom-ops-ai-applications/operations/top_k.mojo, custom-ops-ai-applications/top_k.py, custom-ops-introduction/README.md, custom-ops-introduction/operations/add_one.mojo, custom-ops-introduction/operations/mandelbrot.mojo, custom-ops-introduction/operations/vector_addition.mojo, custom-ops-matrix-multiplication/benchmarks.mojo, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo, gpu-functions-mojo/README.md, gpu-functions-mojo/grayscale.mojo, gpu-functions-mojo/mandelbrot.mojo, gpu-functions-mojo/naive_matrix_multiplication.mojo, gpu-functions-mojo/vector_addition.mojo
The datatypes for custom ops changed recently from `ManagedTensorSlice` to `OutputTensor` and `InputTensor`. This updates all code around the custom ops and benchmarks to build correctly on the latest MAX nightlies.
Additionally, we've reworked the GPU function examples to be cleaner through the use of LayoutTensor, so this brings those updates back into this recipe.
=> Update custom ops and GPU function recipes for the latest MAX nightlies

custom-ops-matrix-multiplication/benchmarks.mojo, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo
1. Change MMA_K Instruction shape for the "tensor_core" benchmark to conform with shape+stride of Inputs
ref: https://github.com/NVIDIA/cutlass/blob/df18f5e4f5de76bed8be1de8e4c245f2f5ec3020/include/cute/atom/mma_traits_sm80.hpp#L147-L160
1. Registered a "tensor_core" benchmark to benchmarks
=> Fix tensor core instruction shape

gpu-functions-mojo/README.md
I did some copyediting and reformatting of the `README.md` for the `gpu_functions` recipe.
In the corresponding Linear ticket [DOCS-780: Provide a review of the Direct GPU Kernels with Mojo recipe](https://linear.app/modularml/issue/DOCS-780/provide-a-review-of-the-direct-gpu-kernels-with-mojo-recipe), I raised a question about whether this should be both linking to the GPU requirements **and** explicitly stating them inline. But I also noticed that some of the other recipes do the same thing, so I decided to leave it as is for now.
=> [docs] Initial copyediting and reformatting for gpu_functions README

custom-ops-ai-applications/README.md, custom-ops-ai-applications/pyproject.toml, custom-ops-introduction/README.md, custom-ops-introduction/pyproject.toml, custom-ops-matrix-multiplication/README.md, custom-ops-matrix-multiplication/pyproject.toml, gpu-functions-mojo/README.md, gpu-functions-mojo/pyproject.toml
Magic 0.7.1 will add the ability to retrieve recipes directly, so this converts the installation instructions over to use the new retrieval functionality rather than Git cloning.
To stabilize the GPU programming examples, they have all been pinned to today's 25.2.0.dev2025031005 MAX nightly. I hand-verified each target in all of these repositories to run on an NVIDIA GPU as of that nightly. We can move them up to newer nightlies once those are tested to add new features required for the demos.
=> Switch GPU programming recipes to use Magic retrieval, pin to current MAX nightly

custom-ops-ai-applications/README.md, custom-ops-introduction/README.md, custom-ops-matrix-multiplication/README.md, gpu-functions-mojo/README.md, gpu-functions-mojo/naive_matrix_multiplication.mojo, gpu-functions-mojo/vector_addition.mojo
In the just-released Magic 0.7.2, version tags are no longer needed for retrieval of Magic recipes, it will pull the most recent version in the repository by default. This removes those tags to make the READMEs version-independent.
Additionally, Abdul pointed out a few places where the examples could be simplified with no functional changes, so those edits have been made in the code and READMEs.
=> Have programmability recipes use the latest version on Magic retrieval

custom-ops-matrix-multiplication/README.md
The matrix multiplication recipe had a few links that were relative to locations in the API docs that 404ed when placed in the recipe, so this updates those to direct links to the relevant items in the API documentation site.
=> Fix some of the reference links in the matrix multiplication recipe

custom-ops-matrix-multiplication/README.md, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo
This makes a couple of changes that I think improve the recipe, some of which might be controversial.
- Remove the kernel signatures for all the kernels except the first one and the last one. Kernels 2-6 have almost the same signature, and I note the addition of new parameters to the signature.
- In kernel 3, break down the code sample and explain it stepwise. The next 3 kernels all use the same basic structure.
- Remove the `bidx` and `bidy` temporary variables, which were only used in one place in each kernel. Removing them made the kernels more consistent.
@BradLarson feel free to merge this if it feels like an overall improvement to you. If you're on the fence, let's leave it and I can rework it post-GTC.
=> Break down discussion of tiled kernel, remove excess code.

custom-ops-ai-applications/pyproject.toml, custom-ops-introduction/pyproject.toml, custom-ops-matrix-multiplication/pyproject.toml, gpu-functions-mojo/pyproject.toml, max-serve-anythingllm/pyproject.toml, max-serve-open-webui/pyproject.toml
Tested that these all work on ubunutu 22.04 GPU and macos CPU
=> Lock max and max-pipelines versions to latest nightly

custom-ops-ai-applications/fused_attention.py, custom-ops-ai-applications/operations/fused_attention.mojo, custom-ops-ai-applications/operations/top_k.mojo, custom-ops-ai-applications/pyproject.toml, custom-ops-ai-applications/top_k.py, custom-ops-introduction/README.md, custom-ops-introduction/add_one.py, custom-ops-introduction/mandelbrot.py, custom-ops-introduction/operations/add_one.mojo, custom-ops-introduction/operations/mandelbrot.mojo, custom-ops-introduction/operations/vector_addition.mojo, custom-ops-introduction/pyproject.toml, custom-ops-introduction/vector_addition.py, custom-ops-matrix-multiplication/benchmarks.mojo, custom-ops-matrix-multiplication/matrix_multiplication.py, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo, custom-ops-matrix-multiplication/pyproject.toml, gpu-functions-mojo/README.md, gpu-functions-mojo/naive_matrix_multiplication.mojo, gpu-functions-mojo/pyproject.toml, gpu-functions-mojo/vector_addition.mojo
Significant enhancements have been made to the way that custom operations are loaded as part of a graph since the previous MAX nightly these examples were pinned to. Additionally, StringLiteral is being phased out in favor of StaticString in some of the operation interfaces.
Finally, some unsafe operations that had previously prevented upgrading the MAX version for these examples have been fixed, so it is now possible to move all of them up to track the current nightly. However, I'm still using a pinned nightly for these, to be safe.
=> Updating the GPU programming examples to the latest MAX nightly

gpu-functions-mojo/README.md, gpu-functions-mojo/grayscale.mojo, gpu-functions-mojo/mandelbrot.mojo, gpu-functions-mojo/naive_matrix_multiplication.mojo, gpu-functions-mojo/pyproject.toml, gpu-functions-mojo/vector_addition.mojo
We migrated our GPU function examples in the public MAX repository to use capabilities provided by `gpu.host`, such as DeviceContext, in order to align our various GPU programming examples around a single function and buffer dispatch interface. This updates the GPU function recipe code and README to follow the new examples and uses the latest MAX nightly.
=> Update Mojo GPU function examples for using `gpu.host`

custom-ops-ai-applications/benchmarks.mojo, custom-ops-ai-applications/fused_attention.py, custom-ops-ai-applications/operations/fused_attention.mojo, custom-ops-ai-applications/pyproject.toml, custom-ops-ai-applications/top_k.py, custom-ops-introduction/add_one.py, custom-ops-introduction/mandelbrot.py, custom-ops-introduction/pyproject.toml, custom-ops-introduction/vector_addition.py, custom-ops-matrix-multiplication/benchmarks.mojo, custom-ops-matrix-multiplication/matrix_multiplication.py, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo, custom-ops-matrix-multiplication/pyproject.toml
`TensorType` now requires a DeviceRef, so this updates all of the custom operation examples to use that and moves forward the pinned MAX nightly to this morning. Additionally, we weren't actually benchmarking the `block_tiled_vectorized_matrix_multiplication` function, so that has been fixed in the matrix multiplication example.
=> Update custom ops recipes for the 04292025 MAX nightly

mojo-operation-template/.gitignore, mojo-operation-template/README.md, mojo-operation-template/benchmarks.mojo, mojo-operation-template/graph.py, mojo-operation-template/metadata.yaml, mojo-operation-template/mojo_tests/__init__.mojo, mojo-operation-template/mojo_tests/test_correctness.mojo, mojo-operation-template/operations/__init__.mojo, mojo-operation-template/operations/graph_operation.mojo, mojo-operation-template/operations/matrix_multiplication.mojo, mojo-operation-template/pyproject.toml, mojo-operation-template/tests/common.py, mojo-operation-template/tests/conftest.py, mojo-operation-template/tests/test_correctness.py
This creates a recipe for a starter template that can be used to modify, benchmark, and test a Mojo custom operation as part of a simple one-element graph.
=> Add a template for Mojo custom operation development

custom-ops-ai-applications/operations/top_k.mojo, custom-ops-ai-applications/pyproject.toml, custom-ops-introduction/mandelbrot.py, custom-ops-introduction/pyproject.toml, custom-ops-matrix-multiplication/operations/matrix_multiplication.mojo, custom-ops-matrix-multiplication/pyproject.toml
In addition to updating the custom ops recipes for the latest nightly, this also removes a no-longer-needed operation packaging step that was confusing the graph compiler.
=> Update custom ops recipes for 20250509 nightly

ai-weather-agent/backend/pyproject.toml, ai-weather-agent/pixi.toml, autodoc-repo-chat-agent/pyproject.toml, code-execution-sandbox-agent-with-e2b/pyproject.toml, custom-ops-ai-applications/pyproject.toml, custom-ops-introduction/pyproject.toml, custom-ops-matrix-multiplication/pyproject.toml, deepseek-qwen-autogen-agent/pyproject.toml, gpu-functions-mojo/pyproject.toml, max-offline-inference/pyproject.toml, max-serve-anythingllm/pyproject.toml, max-serve-continuous-chat/pyproject.toml, max-serve-multimodal-structured-output/pyproject.toml, max-serve-open-webui/pyproject.toml, max-serve-openai-embeddings/pyproject.toml, max-serve-openai-function-calling/pyproject.toml, mojo-operation-template/pyproject.toml, multimodal-rag-with-colpali-llamavision-reranker/pyproject.toml
Generally, we don't want to include channels we don't need. Our `max-nightly` channel is a superset of `max`, so we don't need both, and we don't use anything from the community channel (AFAICT).
Additionally, we should generally put conda-forge first, as this helps with solve times since most dependencies will come from there.
=> Remove unused channels, rearrange to put conda-forge first

autodoc-repo-chat-agent/README.md, autodoc-repo-chat-agent/pyproject.toml, autodoc-repo-chat-agent/uv.lock
- Update pyproject: Replace pixi tasks with poe (poethepoet)
- Update pyproject: Replace max-pipelines with modular package and `max serve`
- Update readme: replace magic with add uv and poe
- Update readme: replace magic init --from with git sparse-checkout
=> Migrate autodoc to uv/pip

ai-weather-agent/Procfile, ai-weather-agent/Procfile.clean, code-execution-sandbox-agent-with-e2b/pyproject.toml, deepseek-qwen-autogen-agent/pyproject.toml, max-serve-anythingllm/pyproject.toml, max-serve-continuous-chat/Procfile, max-serve-continuous-chat/Procfile.clean, max-serve-continuous-chat/README.md, max-serve-multimodal-structured-output/README.md, max-serve-multimodal-structured-output/pyproject.toml, max-serve-open-webui/Procfile.clean, max-serve-open-webui/pyproject.toml, multimodal-rag-with-colpali-llamavision-reranker/Procfile, multimodal-rag-with-colpali-llamavision-reranker/Procfile.clean
As of 25.3 `max-pipelines` is deprecated. I plan to remove this alias in 25.4.
=> Rename max-pipelines to max

mojo-operation-template/README.md, mojo-operation-template/benchmarks.mojo, mojo-operation-template/debug_amd.sh, mojo-operation-template/graph.py, mojo-operation-template/metadata.yaml, mojo-operation-template/operations/graph_operation.mojo, mojo-operation-template/operations/matrix_multiplication.mojo, mojo-operation-template/pyproject.toml, mojo-operation-template/tests/common.py
Since the last hackathon, we've moved from Magic to Pixi and made some updates to the syntax of graph operations and Mojo. This updates for all of those changes, and moves the pinned version of MAX to today's nightly release.
I've tested all but the AMD targets locally.
=> Update Mojo operation template for Pixi and the latest MAX nightly
